language: ruby
before_script:
  - cp config/database.yml{.example,}
  - psql -c 'create database usergroup_test;' -U postgres
  - cp config/application.yml{.example,}
  - bundle exec rake db:migrate db:test:prepare
script: "bundle exec rake spec"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
